# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/jrluser/Downloads/Linux_Unreal_Engine_5.1.0
GAMEPROJECTFILE =/home/jrluser/Documents/Unreal Projects/RGB-D_Fusion/RGBDImmersion.uproject

TARGETS = \
	RGBDImmersion-Linux-DebugGame  \
	RGBDImmersion-Linux-Shipping  \
	RGBDImmersion \
	RGBDImmersionEditor-Linux-DebugGame  \
	RGBDImmersionEditor-Linux-Shipping  \
	RGBDImmersionEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RGBDImmersionEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RGBDImmersionEditor-Linux-Debug


RGBDImmersion-Linux-DebugGame:
	 $(PROJECTBUILD) RGBDImmersion Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RGBDImmersion-Linux-Shipping:
	 $(PROJECTBUILD) RGBDImmersion Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RGBDImmersion:
	 $(PROJECTBUILD) RGBDImmersion Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

RGBDImmersionEditor-Linux-DebugGame:
	 $(PROJECTBUILD) RGBDImmersionEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RGBDImmersionEditor-Linux-Shipping:
	 $(PROJECTBUILD) RGBDImmersionEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RGBDImmersionEditor:
	 $(PROJECTBUILD) RGBDImmersionEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
